# Site settings
# -------------
baseurl : /1617_webd4 # the subpath of your site, e.g. /blog
colour  : primary
language: nl

# SEO
# ---
title      : &title WEBD-IV
description: Web Design IV.
author     : Olivier Parent
# tracking_id: "XX-XXXXXXXX-X"
# url        :
# image      :

# Build settings
# --------------
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
exclude:
  - src/
  - Gemfile
  - README.md